Displays flag icons instead of language tags
edmcouncil/html-pages pull request #117
Opened 2022-01-27 02:03 UTC by dasawanaka

I had problems with my fork, I moved the code to this branch.

Issue: #104 
Previous pull request: #105

2022-02-01 08:46 UTC, mereolog requested changes
Some flags are missing, e.g., the flag of Norway:

![image](https://user-images.githubusercontent.com/11171688/151937796-18c559a1-d1a5-4e9f-bd4e-ca1aaec98cab.png)

2022-02-03 07:35 UTC, dasawanaka commented
> Some flags are missing

Give all flags of countries that do not appear and I will add them manually, the package used does not contain all, as you can see, it contains a lot but not everything

2022-02-03 09:46 UTC, dasawanaka commented
Now i check this countries and update description on pr
[image](https://user-images.githubusercontent.com/26776168/152318023-bc6305e8-c5b8-4b8b-adad-292cd17d94d4.png)
from [country](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FCountryRepresentation%2FCountry) instancess

TODO check:
- [ ] [Guernsey](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FGuernsey)
- [ ] [New Zealand](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FNewZealand)
- [ ] [Saint Lucia](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FSaintLucia)
- [ ] [Bhutan](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FBhutan)
- [ ] [Congo Democratic Republic Of](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FCongoDemocraticRepublicOf)
- [ ] [Indonesia](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FIndonesia)
- [ ] [Malaysia](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FMalaysia)
- [ ] [San Marino](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FSanMarino)
- [ ] [Uganda](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FUganda)
- [ ] [Australia](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FAustralia)
- [ ] [Brunei Darussalam](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FBruneiDarussalam)
- [ ] [France](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FFrance)
- [ ] [Ukraine](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FUkraine)
- [ ] [Oman](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FOman)
- [ ] [Croatia](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FCroatia)
- [ ] [Malta](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FMalta)
- [ ] [Mongolia](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FMongolia)
- [ ] [Papua New Guinea](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FPapuaNewGuinea)
- [ ] [Malawi](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FMalawi)
- [ ] [Turkey](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FTurkey)
- [ ] [Senegal](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FSenegal)
- [ ] [Belize](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FBelize)
- [ ] [Northern Mariana Islands (the)](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FNorthernMarianaIslands)
- [ ] [Haiti](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FHaiti)
- [ ] [Uzbekistan](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FUzbekistan)
- [ ] [Hungary](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FHungary)
- [ ] [Cameroon](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FCameroon)
- [ ] [Montenegro](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FMontenegro)
- [ ] [Israel](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FIsrael)
- [ ] [Sri Lanka](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FSriLanka)
- [ ] [Mauritania](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FMauritania)
- [ ] [United States Minor Outlying Islands (the)](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FUnitedStatesMinorOutlyingIslands)
- [ ] [Zambia](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FZambia)
- [ ] [Thailand](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FThailand)
- [ ] [Macao](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FMacao)
- [ ] [Samoa](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FSamoa)
- [ ] [Guam](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FGuam)
- [ ] [Tunisia](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FTunisia)
- [ ] [Taiwan (Province of China)](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FTaiwan)
- [ ] [United States of America (the)](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FUnitedStatesOfAmerica)
- [ ] [Libya](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FLibya)
- [ ] [Tuvalu](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FTuvalu)
- [ ] [Burkina Faso](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FBurkinaFaso)
- [ ] [Curaçao](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FCuracao)
- [ ] [Germany](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FGermany)
- [ ] [Yemen](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FYemen)
- [ ] [Grenada](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FGrenada)
- [ ] [Singapore](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FSingapore)
- [ ] [Belarus](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FBelarus)
- [ ] [Fiji](http [...]

2022-02-03 09:58 UTC, patrycjamia commented
https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/MarketsIndividuals/Exchange-DOSE
![image](https://user-images.githubusercontent.com/26431993/152320586-68bc4f7e-d537-4679-80d1-828d94e215a1.png)

2022-02-03 10:02 UTC, mereolog commented
> https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/MarketsIndividuals/Exchange-DOSE
> ![image](https://user-images.githubusercontent.com/26431993/152320586-68bc4f7e-d537-4679-80d1-828d94e215a1.png)

This is a problem with FIBO, not us.
I will raise a separate issue for this.

2022-02-03 10:14 UTC, patrycjamia commented
no German flag
https://www.omg.org/spec/LCC/Languages/ISO639-1-LanguageCodes/Tonga-TongaIslands
![image](https://user-images.githubusercontent.com/26431993/152323015-cd5fb73b-fff3-47cc-a2ea-670b1f1a500c.png)

2022-02-03 10:21 UTC, patrycjamia commented
no Lithuanian flag
https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/EuropeanJurisdiction/NorthernEuropeGovernmentEntitiesAndJurisdictions/LithuanianEntity

2022-02-03 12:31 UTC, patrycjamia commented
no Kyrgyzstan flag: ky
https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/AsianJurisdiction/CentralAsiaGovernmentEntitiesAndJurisdictions/GovernmentOfTheKyrgyzRepublic

2022-02-03 12:34 UTC, patrycjamia commented
no Mongolia flag: mn
https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/AsianJurisdiction/EasternAsiaGovernmentEntitiesAndJurisdictions/GovernmentOfMongolia

2022-02-04 08:45 UTC, patrycjamia commented
https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/AsianJurisdiction/SoutheasternAsiaGovernmentEntitiesAndJurisdictions/GovernmentOfTheDemocraticRepublicOfTimor-Leste
![image](https://user-images.githubusercontent.com/26431993/152498831-30e9b4ee-0edb-4255-9d0f-1ec31583cfd0.png)

2022-02-04 10:33 UTC, patrycjamia commented
In this example, the tag displays the Latin language. It would have to be considered whether to display the 'la' tag, as the flag in this example will not display.

https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/EuropeanJurisdiction/SouthernEuropeGovernmentEntitiesAndJurisdictions/GovernmentOfTheHolySee

2022-02-04 10:33 UTC, dasawanaka commented
>  ![image](https://user-images.githubusercontent.com/26431993/152498831-30e9b4ee-0edb-4255-9d0f-1ec31583cfd0.png)

I am processing only 2 letter language tags, I will fix it to include 3 letter tags as well.

2022-02-04 10:48 UTC, patrycjamia commented
> In this example, the tag displays the Latin language. It would have to be considered whether to display the 'la' tag, as the flag in this example will not display.
> 
> https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/EuropeanJurisdiction/SouthernEuropeGovernmentEntitiesAndJurisdictions/GovernmentOfTheHolySee

same with Kurdish language: ku
https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/AsianJurisdiction/WesternAsiaGovernmentEntitiesAndJurisdictions/GovernmentOfTheRepublicOfIraq

2022-02-08 12:06 UTC, patrycjamia requested changes
My comments are above.

2022-02-08 15:43 UTC, rr-adam commented
missing flags left from [this comment](https://github.com/edmcouncil/html-pages/pull/117#issuecomment-1028794943)'s country list

- no [South Africa](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FSouthAfrica) flags: ve, st, tn, ts, xh, ss, zu, nr, af

- no [Switzerland](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FSwitzerland) flags: rm

- no [Madagascar](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FMadagascar) flags: mg

- no [Vanuatu](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FVanuatu) flags: bi

- no [Denmark](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FDenmark) flags: da

- no [Suriname](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FSuriname) flags: nl

- no [Greenland](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FGreenland) flags: (da), kl

- no [Holy See (the)](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FHolySee) flags: la

2022-02-14 08:16 UTC, merged

2022-02-14 13:35 UTC, dasawanaka commented
> In this example, the tag displays the Latin language. It would have to be considered whether to display the 'la' tag, as the flag in this example will not display.
> 
> https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/EuropeanJurisdiction/SouthernEuropeGovernmentEntitiesAndJurisdictions/GovernmentOfTheHolySee

Which flag we should display on latin language?