IDMP article design and product links
edmcouncil/html-pages pull request #197
Opened 2022-05-21 15:06 UTC by rr-adam

fixes: #196 

There is now IDMP product list. On each product page there is a list of downloadable content. Articles now use typography and styling from the ontology viewer design.

**The actual descriptions/text content might need to be changed**.

# Article example:

![image](https://user-images.githubusercontent.com/87621210/169657272-be96eb4d-22c1-4a5d-bd82-736966213749.png)

# Downloads example:

![image](https://user-images.githubusercontent.com/87621210/169656813-fa80c4d0-65dc-46dd-9355-567770d2262f.png)

2022-05-23 07:54 UTC, mereolog submitted a review, later dismissed

2022-05-25 08:24 UTC, dasawanaka requested changes
Looks ok, but fibo and auto look different, this is not how it should be, all pages should look the same. Can you make same changes in ither sites?

2022-06-03 05:39 UTC, patrycjamia approved these changes

2022-06-03 08:05 UTC, mereolog approved these changes

2022-06-03 08:06 UTC, merged