210 statistics should report time machine instance data
edmcouncil/html-pages pull request #211
Opened 2022-06-22 12:08 UTC by patrycjamia

Signed-off-by: Patrycja Miazek <patrycja.miazek@makolab.com>

Statistics are only displayed for stamble. Probably the problem is on the frontend side. I've fixed it, but I can't test it locally, so I don't know if it will work. These changes should be tested on dev.
Fixed: #210

2022-06-22 13:59 UTC, mereolog requested changes
The fix does not work when I ran in docker:
![image](https://user-images.githubusercontent.com/11171688/175047629-2cfae1bc-6ce5-4e45-b3cd-ab31fdb65f2c.png)
@patrycjamia I think you can test your changes locally using docker.

2022-06-22 17:13 UTC, rr-adam requested changes
The problem is with frontend. With the changes requests go to
`/fibo/ontology/%7Bversion%7Dapi/stats`

The "{version}" needs to be replaced in updateServers method in Ontology.vue (if-else statement lines 1287-1311). Stat server is stored in "this.statsServer". It will look the same as others.

Then there needs to be a watcher in StatsComponent.vue that will call "fetchStats" on "statsServer" prop update (otherwise correct stats will fetch only on website refresh).

These two changes and it should work properly

2022-06-23 11:19 UTC, mereolog approved these changes

2022-06-23 13:41 UTC, rr-adam approved these changes

2022-06-23 13:42 UTC, merged