Launching pad for IDMP Ontology
edmcouncil/html-pages pull request #259
Opened 2022-09-27 14:23 UTC by rr-adam

closes: #256 

Added IDMP to Home page menu and quick access list.

---

![image](https://user-images.githubusercontent.com/87621210/192552391-ad1374df-1616-4e12-9745-0b264818ee8e.png)

---

![image](https://user-images.githubusercontent.com/87621210/192552447-4859677a-44ee-4f59-b19f-390f23c0d37c.png)

2022-09-29 13:43 UTC, mereolog submitted a review, later dismissed
DO NOT MERGE THIS YET!!!

2022-09-30 07:50 UTC, dasawanaka requested changes
Additional panel in the slider with idmp information is missing

2022-09-30 08:24 UTC, rosolowski commented
IDMP slide added

![image](https://user-images.githubusercontent.com/87621210/193226370-fa20c1f0-1bb6-4e74-aa34-8d8e0f2ee593.png)

2022-09-30 08:37 UTC, mereolog approved these changes

2022-09-30 09:04 UTC, merged