Added docker file
edmcouncil/html-pages pull request #339
Opened 2023-02-10 12:58 UTC by patrycjamia

Signed-off-by: Patrycja Miazek <patrycja.miazek@makolab.com>

2023-02-15 15:05 UTC, mereolog requested changes
@patrycjamia add docker run instructions to readme.md.

2023-02-15 15:10 UTC, dasawanaka approved these changes, later dismissed

2023-02-16 10:05 UTC, dasawanaka approved these changes

2023-02-16 10:16 UTC, mereolog approved these changes

2023-02-16 10:16 UTC, merged