Option to reveal all labels for edges in visualization
edmcouncil/html-pages pull request #353
Opened 2023-03-30 14:20 UTC by rr-adam

Closes: #352 

Added a toggle button that can be used to keep edge labels always visible.

Other changes:
- Font size of connection label was reduced to make it different from node label
- Improved node distance slider to update in real time and increased range from (20-200) to (10-300)

### Preview:

![image](https://user-images.githubusercontent.com/87621210/228865633-ef48f6ec-4b4a-4382-9d05-b2261007c6c3.png)

2023-03-30 14:50 UTC, mereolog requested changes
@rr-adam can we have 'Display all edge labels' (or at least 'Display edge labels') instead of 'Keep edge labels'?

2023-03-30 15:58 UTC, mereolog approved these changes

2023-03-30 18:21 UTC, dasawanaka approved these changes

2023-03-31 08:53 UTC, patrycjamia approved these changes

2023-03-31 08:53 UTC, merged