Add tooltip-like explanations of the onto-viewer conventions
edmcouncil/html-pages pull request #366
Opened 2023-05-16 08:41 UTC by rr-adam

closes: #364 

Added tooltips that can be used to define or explain elements of the app.

---

### Definition tooltip

Text that has definition tooltip has a dashed underline. When user hovers over the text it will show the tooltip.

![image](https://github.com/edmcouncil/html-pages/assets/87621210/7c1173fc-ac17-41c9-84c7-0f626c13f50f)

### Explanation tooltip

If some element has explanation tooltip there will be a question mark icon next to it. When user hovers over the icon the tooltip will appear.

![image](https://github.com/edmcouncil/html-pages/assets/87621210/961205b3-c055-4ce1-87be-009d54f31e55)

2023-05-16 09:00 UTC, mereolog requested changes
The righthand side ? on the page for https://www.omg.org/spec/Commons/Documents/Specification does not display a tooltip (macOS Ventura, Chrome and Safari):

![image](https://github.com/edmcouncil/html-pages/assets/11171688/9a234b0d-e0e8-46c0-9658-90fc3d3e553c)

2023-05-18 09:17 UTC, mereolog approved these changes

2023-05-18 12:33 UTC, patrycjamia approved these changes

2023-05-18 13:17 UTC, dasawanaka approved these changes

2023-05-22 09:04 UTC, merged