Adaptation to axiom separation
edmcouncil/html-pages pull request #368
Opened 2023-05-29 09:51 UTC by rr-adam

closes: #367 

Frontend will now work with the new type introduced in https://github.com/edmcouncil/onto-viewer/pull/356

![image](https://github.com/edmcouncil/html-pages/assets/87621210/6237e1ec-bcaf-4ec3-b35d-a50c57cd010f)

2023-05-29 11:17 UTC, mereolog requested changes
There is a difference between DEV and PROD, e.g., https://www.omg.org/spec/Commons/QuantitiesAndUnits/hasQuantityKind:

### DEV:
![image](https://github.com/edmcouncil/html-pages/assets/11171688/407dcc00-3242-4f45-a6d2-df1412704766)

### PROD:
![image](https://github.com/edmcouncil/html-pages/assets/11171688/2084bc1f-6ff3-47cc-ab0a-73e727aa055f)

2023-05-29 11:31 UTC, rosolowski commented
> There is a difference between DEV and PROD, e.g., https://www.omg.org/spec/Commons/QuantitiesAndUnits/hasQuantityKind:
> 

@mereolog 
I think this is might be a problem with the backend. Requests are the same but responses are different:

dev request url: `/idmp/ontology/api/entity?iri=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FQuantitiesAndUnits%2FhasQuantityKind`
prod request url: `/idmp/ontology/api/entity?iri=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FQuantitiesAndUnits%2FhasQuantityKind`

![image](https://github.com/edmcouncil/html-pages/assets/87621210/b51a585a-72f9-47cf-8a5d-45806234e12f)

2023-05-29 13:13 UTC, mereolog commented
> > There is a difference between DEV and PROD, e.g., https://www.omg.org/spec/Commons/QuantitiesAndUnits/hasQuantityKind:
> 
> @mereolog I think this is might be a problem with the backend. Requests are the same but responses are different:
> 
> dev request url: `/idmp/ontology/api/entity?iri=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FQuantitiesAndUnits%2FhasQuantityKind` prod request url: `/idmp/ontology/api/entity?iri=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FQuantitiesAndUnits%2FhasQuantityKind`
> 
> ![image](https://user-images.githubusercontent.com/87621210/241721081-b51a585a-72f9-47cf-8a5d-45806234e12f.png)



> > There is a difference between DEV and PROD, e.g., https://www.omg.org/spec/Commons/QuantitiesAndUnits/hasQuantityKind:
> 
> @mereolog I think this is might be a problem with the backend. Requests are the same but responses are different:
> 
> dev request url: `/idmp/ontology/api/entity?iri=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FQuantitiesAndUnits%2FhasQuantityKind` prod request url: `/idmp/ontology/api/entity?iri=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FQuantitiesAndUnits%2FhasQuantityKind`
> 
> ![image](https://user-images.githubusercontent.com/87621210/241721081-b51a585a-72f9-47cf-8a5d-45806234e12f.png)

See: https://github.com/edmcouncil/onto-viewer/pull/353#pullrequestreview-1449476542.

2023-05-30 06:42 UTC, mereolog approved these changes

2023-05-31 04:12 UTC, dasawanaka approved these changes

2023-05-31 07:14 UTC, patrycjamia approved these changes

2023-06-01 06:39 UTC, merged